config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  post 'create-verification-session', to: 'verification_sessions#create'
  get 'verification-webhook', to: 'verification_sessions#webhook'
  post 'verification-webhook', to: 'verification_sessions#webhook'
  put 'verification-webhook', to: 'verification_sessions#webhook'
  get 'verification_report/:id', to: 'verification_sessions#verification_report'
  post 'verifications', to: 'verification_sessions#search'
  get 'verifications', to: 'verification_sessions#index'
  get 'verifications/:id', to: 'verification_sessions#show', as: :retrieve_verification
  get 'submitted', to: 'pages#submitted', as: :submitted
  resources :events, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def home
  end

  def submitted
  end
end

app/controllers/verification_sessions_controller.rb
class VerificationSessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
  end

  def create
    verification_session = Stripe::Identity::VerificationSession.create(
      {
        type: 'document',
        metadata: {
          property_uid: 'secr',
        },
        options: {
          document: {
            allowed_types: %w[driving_license passport id_card],
            require_live_capture: true,
            require_matching_selfie: true
          }
        },
      })

    render json: { client_secret: verification_session.client_secret }
  end

  def webhook
    event = nil

    # Verify webhook signature and extract the event
    # See https://stripe.com/docs/webhooks/signatures for more information.
    begin
      sig_header = request.env['HTTP_STRIPE_SIGNATURE']
      payload = request.body.read
      return head :ok if payload.empty?

      Event.create(body: payload)

      event = Stripe::Webhook.construct_event(payload, sig_header, Stripe.api_key)
      puts event.inspect

      my_logger = Logger.new("#{Rails.root}/log/stripe.log")
      my_logger.info(event.inspect)
    rescue JSON::ParserError => e
      # Invalid payload
      puts e.inspect
      my_logger = Logger.new("#{Rails.root}/log/stripe.log")
      my_logger.error(e.inspect)
      return head :bad_request
    rescue Stripe::SignatureVerificationError => e
      # Invalid signature
      puts e.inspect
      my_logger = Logger.new("#{Rails.root}/log/stripe.log")
      my_logger.error(e.inspect)
      return head :bad_request
    end

    head :ok
  end

  def show
    @data = Stripe::Identity::VerificationSession.retrieve(
      id: params[:id],
      expand: [
        'verified_outputs',
        'verified_outputs.dob',
        'verified_outputs.id_number',
        'last_verification_report',
        'last_verification_report.document.expiration_date',
        'last_verification_report.document.dob',
        'last_verification_report.document.number',
        'last_verification_report.id_number.dob',
        'last_verification_report.id_number.id_number',
      ])
  end

  def verification_report
    @data = Stripe::Identity::VerificationReport.retrieve(
      id: params[:id],
      expand: [
        'id_number.dob',
        'id_number.id_number',
      ])
  end

  def search
    redirect_to retrieve_verification_path(params[:verification_session_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <div class="m-8 border p-4">
    <p class="mb-2">
      Created: <%= event.created_at %>
    </p>
    <pre><code><%= event.body %></code></pre>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <% @events.each do |event| %>
    <%= render event %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Verify your identity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mx-auto pt-5 text-center">
  <ul>
    <li>
      <p class="mb-4">
        <button id="verify-button"
                class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded"
        >Verify
        </button>
      </p>
    </li>
    <li>
      <p class="mb-6">
        <%= link_to "Retrieve Verification Session", verifications_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>
      </p>
    </li>
    <li>
      <p class="mb-6">
        <%= link_to "Events", events_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>
      </p>
    </li>
  </ul>

  <script type="text/javascript">
    // Set your publishable key: remember to change this to your live publishable key in production
    // See your keys here: https://dashboard.stripe.com/apikeys
    var stripe = Stripe('<%= ENV['STRIPE_PUBLIC_KEY'] %>')

    var verifyButton = document.getElementById('verify-button');

    verifyButton.addEventListener('click', function() {
      // Get the VerificationSession client secret using the server-side
      // endpoint you created in step 3.
      fetch('<%= create_verification_session_url %>', {
        method: 'POST',
      })
        .then(function(response) {
          return response.json();
        })
        .then(function(session) {
          // Show the verification modal.
          return stripe.verifyIdentity(session.client_secret);
        })
        .then(function(result) {
          // If `verifyIdentity` fails, you should display the error message
          // using `error.message`.
          if (result.error) {
            alert(result.error.message);
          } else {
            console.log('result', result)
          }
        })
        .catch(function(error) {
          console.error('Error:', error);
        });
    });
  </script>
</div>

app/views/verification_sessions/index.html.erb
<div class="container mx-auto pt-5 text-center">
  <h2 class="mb-6">Retrieve Verification session</h2>
  <%= form_with url: "/verifications", method: :post do |form| %>
    <%= form.label :verification_session_id, "Search for:" %>
    <%= form.text_field :verification_session_id, class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <%= form.submit "Search", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>
  <% end %>
</div>

app/views/verification_sessions/show.html.erb
<pre><code><%= @data %></code></pre>

app/views/verification_sessions/verification_report.html.erb
<pre><code><%= @data %></code></pre>